[package]
name = "oxicsv"
version = "0.1.0"
authors = ["Alexander Battisti <alexander.battisti@eon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
